/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

import clase.Administrador;
import clase.Musica;
import java.io.File;
import java.util.List;
import clase.Biblioteca;
import javax.swing.JOptionPane;

/**
 *
 * @author dcuyu
 */
public class CargaDeMusicas extends javax.swing.JDialog {
    private List<Musica> musicasTemporales = new java.util.ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CargaDeMusicas.class.getName());

    /**
     * Creates new form InterfazCargaDeMusicas
     */
    public CargaDeMusicas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tblMusicasCargadas.getColumnModel().getColumn(0).setMaxWidth(30);
        tblMusicasCargadas.getColumnModel().getColumn(4).setMaxWidth(100);
        tblMusicasCargadas.getColumnModel().getColumn(5).setMaxWidth(65);
        tblMusicasCargadas.getColumnModel().getColumn(6).setMaxWidth(55);
        tblMusicasCargadas.getColumnModel().getColumn(8).setMaxWidth(50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMusicasCargadas = new javax.swing.JTable();
        btnCargar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        tblMusicasCargadas.setBackground(new java.awt.Color(204, 204, 204));
        tblMusicasCargadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nombre", "Artista", "Album", "Genero", "Duracion", "Tamaño", "Ruta", "Año", "Portada"
            }
        ){
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if(columnIndex == 9){
                    return javax.swing.ImageIcon.class;
                }
                return Object.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }
    );
    tblMusicasCargadas.setRowHeight(100);
    tblMusicasCargadas.getColumnModel().getColumn(0).setResizable(false);
    jScrollPane1.setViewportView(tblMusicasCargadas);

    btnCargar.setText("Cargar");
    btnCargar.addActionListener(this::btnCargarActionPerformed);

    btnGuardar.setText("Guardar");
    btnGuardar.addActionListener(this::btnGuardarActionPerformed);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1140, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(btnCargar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnCargar)
                .addComponent(btnGuardar))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        List<File> mp3s = Administrador.seleccionarArchivos(this);
        musicasTemporales = Administrador.extraerMusicasTemporales(mp3s);
        Administrador.mostrarMusicasEnTabla(musicasTemporales, tblMusicasCargadas);
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int agregadas = Biblioteca.getInstance().agregarSinRepetir(musicasTemporales);
        JOptionPane.showMessageDialog(this,
                "Guardadas: " + agregadas,
                "Biblioteca",
                JOptionPane.INFORMATION_MESSAGE);
        dispose(); // cerrar el dialog
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMusicasCargadas;
    // End of variables declaration//GEN-END:variables
}
