/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import clase.Biblioteca;
import clase.Lista;
import clase.Musica;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import clase.Playlist;
import clase.Reproductor;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author dcuyu
 */
public class Principal extends javax.swing.JFrame {
    private final Biblioteca biblioteca = Biblioteca.getInstance();
    private final Reproductor reproductor = new Reproductor();
   
    private Lista listaActualSeleccionada;
    private Lista listaActualReproduciendo;
    private Musica musicaActualReproduciendo;
    private Timer timerReproduccion;
    
    private int duracionActualSegundos;
    private int tiempoActualSegundos;
    
    /**
     * Creates new form InterfazPrincipal
     */
    public Principal() {
        initComponents();
        
        inicializar();
    }
    
    private void inicializar() {
        configurarTablas();
        configurarSlider();
        configurarTimerReproduccion();
        mostrarBiblioteca();
        mostrarPlaylists();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tglCircular1 = new javax.swing.JToggleButton();
        panPlaylist = new javax.swing.JPanel();
        scpPlaylist = new javax.swing.JScrollPane();
        tblPlaylist = new javax.swing.JTable();
        btnBiblioteca = new javax.swing.JButton();
        btnNuevaPlaylist = new javax.swing.JButton();
        btnEditarPlaylist = new javax.swing.JButton();
        panCanciones = new javax.swing.JPanel();
        scpMusicas = new javax.swing.JScrollPane();
        tblMusicas = new javax.swing.JTable();
        lblTituloLista = new javax.swing.JLabel();
        btnReproducirLista = new javax.swing.JButton();
        panReproduccion = new javax.swing.JPanel();
        lblNombreMusica = new javax.swing.JLabel();
        lblTxtArtista = new javax.swing.JLabel();
        lblTxtGenero = new javax.swing.JLabel();
        lblTxtAlbum = new javax.swing.JLabel();
        lblTxtTamanio = new javax.swing.JLabel();
        lblTxtAnio = new javax.swing.JLabel();
        lblPortada = new javax.swing.JLabel();
        sldReproduccion = new javax.swing.JSlider();
        btnPlayPausa = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        lblTiempoActual = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblAlbum = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblTamanio = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        tglCircular = new javax.swing.JToggleButton();
        tglContinua = new javax.swing.JToggleButton();
        jmbMenu = new javax.swing.JMenuBar();
        menuAdministrador = new javax.swing.JMenu();
        jmiCargarMusicas = new javax.swing.JMenuItem();

        tglCircular1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 10)); // NOI18N
        tglCircular1.setText("🔁");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panPlaylist.setBackground(new java.awt.Color(153, 204, 255));
        panPlaylist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPlaylist.setBackground(new java.awt.Color(21, 153, 245));
        tblPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        scpPlaylist.getViewport().setBackground(new Color(161,214,252));
        tblPlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Playlist", "Id"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        tblPlaylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPlaylistMouseClicked(evt);
            }
        });
        scpPlaylist.setViewportView(tblPlaylist);

        panPlaylist.add(scpPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, 480));

        btnBiblioteca.setBackground(new java.awt.Color(21, 153, 245));
        btnBiblioteca.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnBiblioteca.setForeground(new java.awt.Color(255, 255, 255));
        btnBiblioteca.setText("Biblioteca");
        btnBiblioteca.setToolTipText("");
        btnBiblioteca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBiblioteca.setOpaque(true);
        btnBiblioteca.addActionListener(this::btnBibliotecaActionPerformed);
        panPlaylist.add(btnBiblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 40));

        btnNuevaPlaylist.setBackground(new java.awt.Color(250, 249, 249));
        btnNuevaPlaylist.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnNuevaPlaylist.setForeground(new java.awt.Color(0, 0, 153));
        btnNuevaPlaylist.setText("Nueva");
        btnNuevaPlaylist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevaPlaylist.setBorderPainted(false);
        btnNuevaPlaylist.setOpaque(true);
        btnNuevaPlaylist.addActionListener(this::btnNuevaPlaylistActionPerformed);
        panPlaylist.add(btnNuevaPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 110, -1));

        btnEditarPlaylist.setBackground(new java.awt.Color(250, 249, 249));
        btnEditarPlaylist.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEditarPlaylist.setForeground(new java.awt.Color(0, 0, 153));
        btnEditarPlaylist.setText("Editar");
        btnEditarPlaylist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditarPlaylist.setBorderPainted(false);
        btnEditarPlaylist.setOpaque(true);
        panPlaylist.add(btnEditarPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 110, -1));

        panCanciones.setBackground(new java.awt.Color(153, 204, 255));

        tblMusicas.setBackground(new java.awt.Color(0, 93, 232));
        tblMusicas.setForeground(new java.awt.Color(255, 255, 255));
        scpMusicas.getViewport().setBackground(new Color(120,166,235));
        tblMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Musica", "Id"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        tblMusicas.getColumnModel().getColumn(0).setResizable(false);
        tblMusicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMusicasMouseClicked(evt);
            }
        });
        scpMusicas.setViewportView(tblMusicas);

        lblTituloLista.setBackground(new java.awt.Color(204, 255, 255));
        lblTituloLista.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTituloLista.setText("Nombre");
        lblTituloLista.setMaximumSize(new java.awt.Dimension(250, 45));
        lblTituloLista.setMinimumSize(new java.awt.Dimension(250, 45));
        lblTituloLista.setPreferredSize(new java.awt.Dimension(250, 45));

        btnReproducirLista.setBackground(new java.awt.Color(0, 63, 105));
        btnReproducirLista.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        btnReproducirLista.setForeground(new java.awt.Color(255, 255, 255));
        btnReproducirLista.setText("↳ Reproducir lista ▶");
        btnReproducirLista.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReproducirLista.setOpaque(true);
        btnReproducirLista.addActionListener(this::btnReproducirListaActionPerformed);

        javax.swing.GroupLayout panCancionesLayout = new javax.swing.GroupLayout(panCanciones);
        panCanciones.setLayout(panCancionesLayout);
        panCancionesLayout.setHorizontalGroup(
            panCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCancionesLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReproducirLista, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(scpMusicas, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(lblTituloLista, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panCancionesLayout.setVerticalGroup(
            panCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCancionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloLista, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scpMusicas, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReproducirLista, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panReproduccion.setBackground(new java.awt.Color(73, 134, 190));

        lblNombreMusica.setBackground(new java.awt.Color(153, 204, 255));
        lblNombreMusica.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblNombreMusica.setText("<html><div style='width:250px;'>Nombre Musica</div></html>");

        lblTxtArtista.setBackground(new java.awt.Color(0, 153, 255));
        lblTxtArtista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTxtArtista.setText("Artista:");

        lblTxtGenero.setBackground(new java.awt.Color(0, 153, 255));
        lblTxtGenero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTxtGenero.setText("Genero:");

        lblTxtAlbum.setBackground(new java.awt.Color(0, 153, 255));
        lblTxtAlbum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTxtAlbum.setText("Album:");

        lblTxtTamanio.setBackground(new java.awt.Color(0, 153, 255));
        lblTxtTamanio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTxtTamanio.setText("Tamaño:");

        lblTxtAnio.setBackground(new java.awt.Color(0, 153, 255));
        lblTxtAnio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTxtAnio.setText("Año:");

        lblPortada.setOpaque(true);
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/imagen/SmartPlayerLogo.png"));
        Image originalImage = originalIcon.getImage();

        lblPortada.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                int w = lblPortada.getWidth();
                int h = lblPortada.getHeight();
                if (w > 0 && h > 0) {
                    Image scaled = originalImage.getScaledInstance(w, h, Image.SCALE_SMOOTH);
                    lblPortada.setIcon(new ImageIcon(scaled));
                }
            }
        });

        sldReproduccion.setValue(0);

        btnPlayPausa.setBackground(new java.awt.Color(0, 63, 105));
        btnPlayPausa.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        btnPlayPausa.setForeground(new java.awt.Color(255, 255, 255));
        btnPlayPausa.setText("▶");
        btnPlayPausa.setActionCommand("");
        btnPlayPausa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnPlayPausa.setBorderPainted(false);
        btnPlayPausa.setOpaque(true);
        btnPlayPausa.addActionListener(this::btnPlayPausaActionPerformed);

        btnSiguiente.setBackground(new java.awt.Color(0, 63, 105));
        btnSiguiente.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("⏭");
        btnSiguiente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.setOpaque(true);
        btnSiguiente.addActionListener(this::btnSiguienteActionPerformed);

        btnAnterior.setBackground(new java.awt.Color(0, 63, 105));
        btnAnterior.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        btnAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnAnterior.setText("⏮");
        btnAnterior.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnAnterior.setBorderPainted(false);
        btnAnterior.setOpaque(true);
        btnAnterior.addActionListener(this::btnAnteriorActionPerformed);

        lblTiempoActual.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblTiempoActual.setText("00:00");

        lblDuracion.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblDuracion.setText("00:00");

        lblArtista.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        lblArtista.setText("Nombre del artista");

        lblAlbum.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        lblAlbum.setText("Nombre del album");

        lblGenero.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        lblGenero.setText("Genero de la musica");

        lblTamanio.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        lblTamanio.setText("500 GB");

        lblAnio.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        lblAnio.setText("0000");

        tglCircular.setBackground(new java.awt.Color(0, 63, 105));
        tglCircular.setFont(new java.awt.Font("Segoe UI Symbol", 1, 10)); // NOI18N
        tglCircular.setForeground(new java.awt.Color(255, 255, 255));
        tglCircular.setText("🔁");
        tglCircular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tglCircular.setBorderPainted(false);
        tglCircular.setOpaque(true);
        tglCircular.addActionListener(this::tglCircularActionPerformed);

        tglContinua.setBackground(new java.awt.Color(0, 63, 105));
        tglContinua.setFont(new java.awt.Font("Segoe UI Symbol", 1, 7)); // NOI18N
        tglContinua.setForeground(new java.awt.Color(255, 255, 255));
        tglContinua.setText("▶▶");
        tglContinua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tglContinua.setBorderPainted(false);
        tglContinua.setOpaque(true);
        tglContinua.addActionListener(this::tglContinuaActionPerformed);

        javax.swing.GroupLayout panReproduccionLayout = new javax.swing.GroupLayout(panReproduccion);
        panReproduccion.setLayout(panReproduccionLayout);
        panReproduccionLayout.setHorizontalGroup(
            panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panReproduccionLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panReproduccionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTiempoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldReproduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addComponent(lblNombreMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panReproduccionLayout.createSequentialGroup()
                        .addComponent(lblTxtArtista)
                        .addGap(6, 6, 6)
                        .addComponent(lblArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblTxtAlbum)
                        .addGap(9, 9, 9)
                        .addComponent(lblAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panReproduccionLayout.createSequentialGroup()
                        .addComponent(lblTxtGenero)
                        .addGap(6, 6, 6)
                        .addComponent(lblGenero)
                        .addGap(6, 6, 6)
                        .addComponent(lblTxtAnio)
                        .addGap(6, 6, 6)
                        .addComponent(lblAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(lblTxtTamanio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTamanio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panReproduccionLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(tglContinua, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglCircular, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panReproduccionLayout.setVerticalGroup(
            panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panReproduccionLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblNombreMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panReproduccionLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTxtArtista)
                            .addComponent(lblTxtAlbum))))
                .addGap(6, 6, 6)
                .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panReproduccionLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTxtGenero)
                            .addComponent(lblTxtAnio)
                            .addComponent(lblTxtTamanio))))
                .addGap(6, 6, 6)
                .addComponent(lblPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDuracion)
                        .addComponent(lblTiempoActual))
                    .addComponent(sldReproduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPlayPausa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panReproduccionLayout.createSequentialGroup()
                        .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tglCircular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglContinua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        menuAdministrador.setText("Administrador");

        jmiCargarMusicas.setText("Cargar musicas");
        jmiCargarMusicas.addActionListener(this::jmiCargarMusicasActionPerformed);
        menuAdministrador.add(jmiCargarMusicas);

        jmbMenu.add(menuAdministrador);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panReproduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panCanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panReproduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void configurarTablas() {
        ocultarColumna(tblMusicas, 2);
        ocultarColumna(tblPlaylist, 2);

        establecerAnchoMaximo(tblPlaylist, 0, 30);
        establecerAnchoMaximo(tblMusicas, 0, 30);
    }
    
    private void configurarTimerReproduccion() {
        timerReproduccion = new Timer(1000, e -> actualizarProgresoReproduccion());
    }
    
    private void actualizarProgresoReproduccion() {
        if (!reproductor.Reproduciendo()) {
            return;
        }

        tiempoActualSegundos++;

        if (tiempoActualSegundos > duracionActualSegundos) {
            tiempoActualSegundos = duracionActualSegundos;
        }

        sldReproduccion.setValue(tiempoActualSegundos);
        lblTiempoActual.setText(formatearTiempo(tiempoActualSegundos));
    }
    
    private String formatearTiempo(int segundosTotales) {
        int minutos = segundosTotales / 60;
        int segundos = segundosTotales % 60;

        return String.format("%02d:%02d", minutos, segundos);
    }
    
    private void ocultarColumna(javax.swing.JTable tabla, int columna) {
        tabla.getColumnModel().getColumn(columna).setMinWidth(0);
        tabla.getColumnModel().getColumn(columna).setMaxWidth(0);
        tabla.getColumnModel().getColumn(columna).setPreferredWidth(0);
    }

    private void establecerAnchoMaximo(javax.swing.JTable tabla, int columna, int ancho) {
        tabla.getColumnModel().getColumn(columna).setMaxWidth(ancho);
    }
    
    private void configurarSlider() {
        sldReproduccion.setOpaque(true);
        sldReproduccion.setBackground(panReproduccion.getBackground());
        sldReproduccion.setFocusable(false);
        sldReproduccion.setPaintTicks(false);
        sldReproduccion.setPaintLabels(false);
        sldReproduccion.setBorder(null);

        sldReproduccion.setUI(new javax.swing.plaf.basic.BasicSliderUI(sldReproduccion) {
            @Override
            public void paintFocus(Graphics g) {
                // No dibujar borde de foco
            }
            @Override
            public void setThumbLocation(int x, int y) {
                super.setThumbLocation(x, y);
                slider.repaint();
            }
            @Override
            public void paintTrack(Graphics g) {
                Graphics2D g2d = (Graphics2D) g;
                g2d.setRenderingHint(
                        RenderingHints.KEY_ANTIALIASING,
                        RenderingHints.VALUE_ANTIALIAS_ON
                );

                int y = trackRect.y + trackRect.height / 2 - 2;
                int alto = 4;
                g2d.setColor(new java.awt.Color(220, 220, 220));

                g2d.fillRoundRect(
                        trackRect.x,
                        y,
                        trackRect.width,
                        alto,
                        alto,
                        alto
                );
            }
            @Override
            public void paintThumb(Graphics g) {
                Graphics2D g2d = (Graphics2D) g;
                g2d.setRenderingHint(
                        RenderingHints.KEY_ANTIALIASING,
                        RenderingHints.VALUE_ANTIALIAS_ON
                );
                g2d.setColor(new java.awt.Color(0, 122, 255));
               
                int diametro = 16;
                int x = thumbRect.x + (thumbRect.width - diametro) / 2;
                int y = thumbRect.y + (thumbRect.height - diametro) / 2;
                g2d.fillOval(x, y, diametro, diametro);
            }
        });
    }
    
    private void mostrarBiblioteca() {
        Lista listaBiblioteca = biblioteca.getBiblioteca();
        
        cargarMusicasEnTabla(listaBiblioteca.toListAdelante());
        
        listaActualSeleccionada = listaBiblioteca;
        
        lblTituloLista.setText("Biblioteca");
        
        if (listaActualReproduciendo == listaActualSeleccionada
                && musicaActualReproduciendo != null) {
            seleccionarMusicaEnTabla(musicaActualReproduciendo.getId());
        }
        
        seleccionarPlaylistReproduciendo();
    }
    
    private void mostrarPlaylists() {
        DefaultTableModel tabla = (DefaultTableModel)tblPlaylist.getModel();
        tabla.setRowCount(0);
       
        List<Playlist> playlists = biblioteca.getPlaylists();
        
        int no = 1;
        for (Playlist playlist : playlists) {
            
            tabla.addRow(new Object[]{
                no++,
                playlist.getNombre(),
                playlist.getId()
            });
        }
    }
    
    private void cargarMusicasEnTabla(List<Musica> musicas) {
        DefaultTableModel tabla = (DefaultTableModel)tblMusicas.getModel();
        tabla.setRowCount(0);
        
        if (musicas == null) {
            return;
        }
        
        int no = 1;
        for (Musica m : musicas) {
            tabla.addRow(new Object[]{ no++, m.toString(), m.getId() });
        }
    }
    
    private String textoHtml(String texto, int width) {
        return "<html><div style='width:" + width + "px;'>" + texto + "</div></html>";
    }
    
    private void mostrarDatosDeMusica() {
        Musica musica = musicaActualReproduciendo;
        if (musica == null) {
            return;
        }
        lblNombreMusica.setText(textoHtml(musica.getNombre(), 300));
        lblArtista.setText(textoHtml(musica.getArtista(), 100));
        lblAlbum.setText(textoHtml(musica.getAlbum(), 100));
        lblGenero.setText(textoHtml(musica.getGenero(), 70));
        lblAnio.setText(textoHtml(musica.anioReal(), 40));
        lblTamanio.setText(textoHtml(musica.formatearTamanio(), 50));
        lblPortada.setIcon(musica.getPortadaGrande(lblPortada.getWidth(), lblPortada.getHeight()));
        lblDuracion.setText(musica.formatearDuracion());
    }
    
    private void abrirPlaylist() {
        int fila = tblPlaylist.getSelectedRow();
        if (fila < 0) return;
        int id = (Integer) tblPlaylist.getValueAt(fila, 2);

        Playlist playlistSeleccionada = biblioteca.buscarPlaylistPorId(id);
        if (playlistSeleccionada == null) return;

        cargarMusicasEnTabla(playlistSeleccionada.toList());
        listaActualSeleccionada = playlistSeleccionada.getPlaylist();
        lblTituloLista.setText("Playlist: " + playlistSeleccionada.getNombre());

        if (listaActualReproduciendo == listaActualSeleccionada && musicaActualReproduciendo != null) {
            seleccionarMusicaEnTabla(musicaActualReproduciendo.getId());
        }
    }

    private void seleccionarPlaylistReproduciendo() {
        if (listaActualReproduciendo == null || musicaActualReproduciendo == null) {
            tblPlaylist.clearSelection();
            return;
        }

        for (int fila = 0; fila < tblPlaylist.getRowCount(); fila++) {
            Object valorId = tblPlaylist.getValueAt(fila, 2);
            if (valorId == null) continue;

            int idPlaylist = Integer.parseInt(valorId.toString());

            for (Playlist playlist : biblioteca.getPlaylists()) {
                if (playlist.getId() == idPlaylist) {
                    if (playlist.getPlaylist() == listaActualReproduciendo) {
                        tblPlaylist.setRowSelectionInterval(fila, fila);
                        return;
                    }
                }
            }
        }

        tblPlaylist.clearSelection();
    }
    
    private boolean seleccionarMusicaEnTabla(int id) {
        for (int fila = 0; fila < tblMusicas.getRowCount(); fila++) {
            Object valor = tblMusicas.getValueAt(fila, 2);
            if (valor != null && Integer.parseInt(valor.toString()) == id) {
                tblMusicas.setRowSelectionInterval(fila, fila);
                return true;
            }
        }
        return false;
    }
    
    private int idMusicaSeleccionada() {
        int fila = tblMusicas.getSelectedRow();
        if (fila < 0) {
            return 0;
        }
        return (Integer) tblMusicas.getValueAt(fila, 2);
    }
    
    private Musica musicaSeleccionada() {
        if (listaActualSeleccionada == null) {
            return null;
        }
        return listaActualSeleccionada.buscarPorId(idMusicaSeleccionada());
    }
   
    private void reproducirMusicaSeleccionada() {
        Musica musica = musicaSeleccionada();
        if (musica == null || listaActualSeleccionada == null) {
            return;
        }

        Musica seleccionada = listaActualSeleccionada.seleccionar(musica);
        if (seleccionada == null) {
            return;
        }

        listaActualReproduciendo = listaActualSeleccionada;
        reproducirMusica(seleccionada);
    }
    
    private void reproducirMusica(Musica musica) {
        if (musica == null) {
            return;
        }
        musicaActualReproduciendo = musica;
        
        duracionActualSegundos = (int) musica.getDuracion();
        tiempoActualSegundos = 0;

        sldReproduccion.setMaximum(duracionActualSegundos);
        sldReproduccion.setValue(0);

        lblTiempoActual.setText("00:00");
        lblDuracion.setText(formatearTiempo(duracionActualSegundos));
        reproductor.Play(musica);
        timerReproduccion.start();
        actualizarInterfazReproduccion();
    }
    
    private void actualizarInterfazReproduccion() {
        btnPlayPausa.setText("⏸️");
        mostrarDatosDeMusica();

        if (listaActualSeleccionada == listaActualReproduciendo) {
            seleccionarMusicaEnTabla(musicaActualReproduciendo.getId());
        }
        if (listaActualReproduciendo == biblioteca.getBiblioteca()) {
            tblPlaylist.clearSelection();
        }
    }

    private void detenerReproduccion() {
        timerReproduccion.stop();
        reproductor.Stop();
        btnPlayPausa.setText("▶");
    }
    
    private void manejarPlayPausa() {
        if (!reproductor.Reproduciendo() && !reproductor.Pausado()) {
            if (listaActualSeleccionada == null) {
                JOptionPane.showMessageDialog(this, "No hay lista seleccionada");
                return;
            }
            if (musicaSeleccionada() == null) {
                JOptionPane.showMessageDialog(this, "Selecciona una musica para reproducir");
                return;
            }

            reproducirMusicaSeleccionada();
            return;
        }

        if (reproductor.Reproduciendo()) {
            reproductor.Pausa();
            btnPlayPausa.setText("▶");
            return;
        }

        if (reproductor.Pausado()) {
            reproductor.Reanudar();
            btnPlayPausa.setText("⏸️");
        }
    }
    
    private void reproducirSiguiente() {
        if (listaActualReproduciendo == null) {
            JOptionPane.showMessageDialog(this, "No hay una lista reproduciendose");
            return;
        }
        if (listaActualReproduciendo.tieneSiguiente()) {
            Musica siguiente = listaActualReproduciendo.siguiente();
            reproducirMusica(siguiente);
            return;
        }

        detenerReproduccion();
    }
    
    private void reproducirAnterior() {
        if (listaActualReproduciendo == null) {
            JOptionPane.showMessageDialog(this, "No hay una lista reproduciendose");
            return;
        }
        if (listaActualReproduciendo.tieneAnterior()) {
            Musica anterior = listaActualReproduciendo.anterior();
            reproducirMusica(anterior);
            return;
        }
        
        detenerReproduccion();
    }
    
    private void reproducirListaActual() {
        if (listaActualSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "No hay lista seleccionada");
            return;
        }

        if (listaActualSeleccionada.estaVacia()) {
            JOptionPane.showMessageDialog(this, "No hay musicas para reproducir");
            return;
        }

        listaActualReproduciendo = listaActualSeleccionada;
        Musica primera = listaActualReproduciendo.primera();

        if (primera == null) {
            JOptionPane.showMessageDialog(this, "No se pudo iniciar la reproduccion");
            return;
        }

        reproducirMusica(primera);
    }
    
    private void jmiCargarMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCargarMusicasActionPerformed
        CargaDeMusicas interfazCargaDeMusicas = new CargaDeMusicas(this, true);
        interfazCargaDeMusicas.setVisible(true);
        mostrarBiblioteca();
    }//GEN-LAST:event_jmiCargarMusicasActionPerformed

    private void btnBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBibliotecaActionPerformed
        mostrarBiblioteca();
    }//GEN-LAST:event_btnBibliotecaActionPerformed

    private void btnNuevaPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaPlaylistActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Nombre de la playlist:");
        if (nombre == null) return; // cancelo
        nombre = nombre.trim();
        if (nombre.isBlank()) {
            JOptionPane.showMessageDialog(this, "Nombre invalido");
            return;
        }
        if (biblioteca.existePlaylist(nombre)) {
            JOptionPane.showMessageDialog(this, "Ya existe una playlist con ese nombre");
            return;
        }
        NuevaPlaylist interfazNuevaPlaylist = new NuevaPlaylist(this, true, nombre);
        interfazNuevaPlaylist.setVisible(true);
        mostrarPlaylists();
        mostrarBiblioteca();
        if (listaActualReproduciendo != biblioteca.getBiblioteca()) {
            seleccionarPlaylistReproduciendo();
            abrirPlaylist();
        }
    }//GEN-LAST:event_btnNuevaPlaylistActionPerformed
    
    private void tblPlaylistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPlaylistMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            abrirPlaylist();
        }
    }//GEN-LAST:event_tblPlaylistMouseClicked

    private void tblMusicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMusicasMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();

            reproducirMusicaSeleccionada();
        }
    }//GEN-LAST:event_tblMusicasMouseClicked

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        reproducirAnterior();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        reproducirSiguiente();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnPlayPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayPausaActionPerformed
        manejarPlayPausa();
    }//GEN-LAST:event_btnPlayPausaActionPerformed

    private void btnReproducirListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproducirListaActionPerformed
        reproducirListaActual();
    }//GEN-LAST:event_btnReproducirListaActionPerformed

    private void tglCircularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglCircularActionPerformed
        if (listaActualReproduciendo != null) {
            listaActualReproduciendo.Circular(tglCircular.isSelected());
        } else {
            tglCircular.setSelected(false);
        }
    }//GEN-LAST:event_tglCircularActionPerformed

    private void tglContinuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglContinuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglContinuaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBiblioteca;
    private javax.swing.JButton btnEditarPlaylist;
    private javax.swing.JButton btnNuevaPlaylist;
    private javax.swing.JButton btnPlayPausa;
    private javax.swing.JButton btnReproducirLista;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JMenuItem jmiCargarMusicas;
    private javax.swing.JLabel lblAlbum;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNombreMusica;
    private javax.swing.JLabel lblPortada;
    private javax.swing.JLabel lblTamanio;
    private javax.swing.JLabel lblTiempoActual;
    private javax.swing.JLabel lblTituloLista;
    private javax.swing.JLabel lblTxtAlbum;
    private javax.swing.JLabel lblTxtAnio;
    private javax.swing.JLabel lblTxtArtista;
    private javax.swing.JLabel lblTxtGenero;
    private javax.swing.JLabel lblTxtTamanio;
    private javax.swing.JMenu menuAdministrador;
    private javax.swing.JPanel panCanciones;
    private javax.swing.JPanel panPlaylist;
    private javax.swing.JPanel panReproduccion;
    private javax.swing.JScrollPane scpMusicas;
    private javax.swing.JScrollPane scpPlaylist;
    private javax.swing.JSlider sldReproduccion;
    private javax.swing.JTable tblMusicas;
    private javax.swing.JTable tblPlaylist;
    private javax.swing.JToggleButton tglCircular;
    private javax.swing.JToggleButton tglCircular1;
    private javax.swing.JToggleButton tglContinua;
    // End of variables declaration//GEN-END:variables
}
