/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import clase.Biblioteca;
import clase.Lista;
import clase.Musica;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import clase.Playlist;
import clase.Reproductor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JOptionPane;

/**
 *
 * @author dcuyu
 */
public class Principal extends javax.swing.JFrame {
    Reproductor reproductor = new Reproductor();
    Lista listaActualSeleccionada;
    Lista listaActualReproduciendo;
    Musica musicaActualSeleccionada;
    Musica musicaActualReproduciendo;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form InterfazPrincipal
     */
    public Principal() {
        initComponents();
        mostrarBiblioteca();
        mostrarPlaylists();
        tblMusicas.getColumnModel().getColumn(2).setMinWidth(0);
        tblMusicas.getColumnModel().getColumn(2).setMaxWidth(0);
        tblPlaylist.getColumnModel().getColumn(2).setMinWidth(0);
        tblPlaylist.getColumnModel().getColumn(2).setMaxWidth(0);
        tblMusicas.getColumnModel().getColumn(2).setPreferredWidth(0);
        tblPlaylist.getColumnModel().getColumn(0).setMaxWidth(30);
        tblMusicas.getColumnModel().getColumn(0).setMaxWidth(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPlaylist = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPlaylist = new javax.swing.JTable();
        btnBiblioteca = new javax.swing.JButton();
        btnNuevaPlaylist = new javax.swing.JButton();
        btnEditarPlaylist = new javax.swing.JButton();
        panCanciones = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMusicas = new javax.swing.JTable();
        lblTituloLista = new javax.swing.JLabel();
        btnReproducirLista = new javax.swing.JButton();
        panReproduccion = new javax.swing.JPanel();
        lblNombreMusica = new javax.swing.JLabel();
        lblTxtArtista = new javax.swing.JLabel();
        lblTxtGenero = new javax.swing.JLabel();
        lblTxtAlbum = new javax.swing.JLabel();
        lblTxtTamanio = new javax.swing.JLabel();
        lblTxtAnio = new javax.swing.JLabel();
        lblPortada = new javax.swing.JLabel();
        sldReproduccion = new javax.swing.JSlider();
        btnPlayPausa = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnRepetir = new javax.swing.JButton();
        lblTiempoActual = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblAlbum = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblTamanio = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        jmbMenu = new javax.swing.JMenuBar();
        menuAdministrador = new javax.swing.JMenu();
        jmiCargarMusicas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panPlaylist.setBackground(new java.awt.Color(153, 204, 255));
        panPlaylist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPlaylist.setBackground(new java.awt.Color(121, 245, 248));
        tblPlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Playlist", "Id"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        tblPlaylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPlaylistMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPlaylist);

        panPlaylist.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, 480));

        btnBiblioteca.setBackground(new java.awt.Color(124, 163, 238));
        btnBiblioteca.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnBiblioteca.setText("Biblioteca");
        btnBiblioteca.setToolTipText("");
        btnBiblioteca.setOpaque(true);
        btnBiblioteca.addActionListener(this::btnBibliotecaActionPerformed);
        panPlaylist.add(btnBiblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 40));

        btnNuevaPlaylist.setText("Nueva");
        btnNuevaPlaylist.addActionListener(this::btnNuevaPlaylistActionPerformed);
        panPlaylist.add(btnNuevaPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 110, -1));

        btnEditarPlaylist.setText("Editar");
        panPlaylist.add(btnEditarPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 110, -1));

        panCanciones.setBackground(new java.awt.Color(153, 204, 255));

        tblMusicas.setBackground(new java.awt.Color(255, 255, 224));
        tblMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Musica", "Id"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        tblMusicas.getColumnModel().getColumn(0).setResizable(false);
        tblMusicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMusicasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMusicas);

        lblTituloLista.setBackground(new java.awt.Color(204, 255, 255));
        lblTituloLista.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTituloLista.setText("Nombre");

        btnReproducirLista.setBackground(new java.awt.Color(204, 255, 204));
        btnReproducirLista.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        btnReproducirLista.setText("↳ Reproducir lista ▶");
        btnReproducirLista.setOpaque(true);

        javax.swing.GroupLayout panCancionesLayout = new javax.swing.GroupLayout(panCanciones);
        panCanciones.setLayout(panCancionesLayout);
        panCancionesLayout.setHorizontalGroup(
            panCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCancionesLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReproducirLista, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(lblTituloLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panCancionesLayout.setVerticalGroup(
            panCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCancionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloLista, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReproducirLista, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panReproduccion.setBackground(new java.awt.Color(73, 134, 190));

        lblNombreMusica.setBackground(new java.awt.Color(153, 204, 255));
        lblNombreMusica.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblNombreMusica.setText("Nombre Musica");
        lblNombreMusica.setText("<html><div style='width:250px;'>Nombre Música</div></html>");

        lblTxtArtista.setBackground(new java.awt.Color(0, 153, 255));
        lblTxtArtista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTxtArtista.setText("Artista:");

        lblTxtGenero.setBackground(new java.awt.Color(0, 153, 255));
        lblTxtGenero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTxtGenero.setText("Genero:");

        lblTxtAlbum.setBackground(new java.awt.Color(0, 153, 255));
        lblTxtAlbum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTxtAlbum.setText("Album:");

        lblTxtTamanio.setBackground(new java.awt.Color(0, 153, 255));
        lblTxtTamanio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTxtTamanio.setText("Tamaño:");

        lblTxtAnio.setBackground(new java.awt.Color(0, 153, 255));
        lblTxtAnio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTxtAnio.setText("Año:");

        lblPortada.setText(".");
        lblPortada.setOpaque(true);

        sldReproduccion.setUI(new javax.swing.plaf.basic.BasicSliderUI(sldReproduccion) {
            @Override
            public void paintThumb(Graphics g) {
                Graphics2D g2d = (Graphics2D) g;
                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                // Color de la bolita
                g2d.setColor(new java.awt.Color(0, 122, 255));

                // Forzamos un tamaño idéntico para que sea un círculo perfecto (16x16 píxeles)
                int diametro = 16;

                // Centramos la bolita verticalmente en el espacio disponible
                int x = thumbRect.x + (thumbRect.width - diametro) / 2;
                int y = thumbRect.y + (thumbRect.height - diametro) / 2;

                // Dibujamos el círculo perfecto
                g2d.fillOval(x, y, diametro, diametro);
            }
        });

        btnPlayPausa.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        btnPlayPausa.setText("▶");
        btnPlayPausa.setActionCommand("");
        btnPlayPausa.addActionListener(this::btnPlayPausaActionPerformed);

        btnSiguiente.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        btnSiguiente.setText("⏭");
        btnSiguiente.addActionListener(this::btnSiguienteActionPerformed);

        btnAnterior.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        btnAnterior.setText("⏮");
        btnAnterior.addActionListener(this::btnAnteriorActionPerformed);

        btnRepetir.setFont(new java.awt.Font("Segoe UI Symbol", 1, 9)); // NOI18N
        btnRepetir.setText("🔁");

        lblTiempoActual.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblTiempoActual.setText("00:00");

        lblDuracion.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblDuracion.setText("00:00");

        lblArtista.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        lblArtista.setText("Nombre del artista");

        lblAlbum.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        lblAlbum.setText("Nombre del album");

        lblGenero.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        lblGenero.setText("Genero de la musica");

        lblTamanio.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        lblTamanio.setText("500 GB");

        lblAnio.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        lblAnio.setText("0000");

        javax.swing.GroupLayout panReproduccionLayout = new javax.swing.GroupLayout(panReproduccion);
        panReproduccion.setLayout(panReproduccionLayout);
        panReproduccionLayout.setHorizontalGroup(
            panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panReproduccionLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panReproduccionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTiempoActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sldReproduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDuracion)
                        .addGap(8, 8, 8))
                    .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblNombreMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panReproduccionLayout.createSequentialGroup()
                            .addComponent(lblTxtArtista)
                            .addGap(6, 6, 6)
                            .addComponent(lblArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(lblTxtAlbum)
                            .addGap(9, 9, 9)
                            .addComponent(lblAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panReproduccionLayout.createSequentialGroup()
                            .addComponent(lblTxtGenero)
                            .addGap(6, 6, 6)
                            .addComponent(lblGenero)
                            .addGap(6, 6, 6)
                            .addComponent(lblTxtAnio)
                            .addGap(6, 6, 6)
                            .addComponent(lblAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)
                            .addComponent(lblTxtTamanio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblTamanio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(panReproduccionLayout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPlayPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnRepetir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panReproduccionLayout.setVerticalGroup(
            panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panReproduccionLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblNombreMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panReproduccionLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTxtArtista)
                            .addComponent(lblTxtAlbum))))
                .addGap(6, 6, 6)
                .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panReproduccionLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTxtGenero)
                            .addComponent(lblTxtAnio)
                            .addComponent(lblTxtTamanio))))
                .addGap(6, 6, 6)
                .addComponent(lblPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panReproduccionLayout.createSequentialGroup()
                        .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDuracion)
                            .addComponent(lblTiempoActual))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panReproduccionLayout.createSequentialGroup()
                        .addComponent(sldReproduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPlayPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(panReproduccionLayout.createSequentialGroup()
                        .addComponent(btnRepetir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        menuAdministrador.setText("Administrador");

        jmiCargarMusicas.setText("Cargar musicas");
        jmiCargarMusicas.addActionListener(this::jmiCargarMusicasActionPerformed);
        menuAdministrador.add(jmiCargarMusicas);

        jmbMenu.add(menuAdministrador);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panReproduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panCanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panReproduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void mostrarBiblioteca() {
        cargarMusicasEnTabla(Biblioteca.getInstance().getBiblioteca().toListAdelante());
        listaActualSeleccionada = Biblioteca.getInstance().getBiblioteca();
        lblTituloLista.setText("<html><div style='width:120px;'>" + "Biblioteca" + "</div></html>");
    }
    
    private void mostrarPlaylists() {
        DefaultTableModel tabla = (DefaultTableModel)tblPlaylist.getModel();
        tabla.setRowCount(0);

        List<Playlist> playlists = Biblioteca.getInstance().getPlaylists();
        int no = 1;
        for (Playlist playlist : playlists) {
            tabla.addRow(new Object[]{ no++, playlist.getNombre(), playlist.getId() });
        }
    }
    
    private void cargarMusicasEnTabla(List<Musica> musicas) {
        DefaultTableModel tabla = (DefaultTableModel)tblMusicas.getModel();
        tabla.setRowCount(0);
        int no = 1;
        for (Musica m : musicas) {
            tabla.addRow(new Object[]{ no++, m.toString(), m.getId() });
        }
    }
    
    private void abrirPlaylist() {
        int fila = tblPlaylist.getSelectedRow();
        if (fila < 0) return;
        int id = (Integer) tblPlaylist.getValueAt(fila, 2);

        Playlist playlistSeleccionada = null;
        for (Playlist playlist : Biblioteca.getInstance().getPlaylists()) {
            if (playlist.getId() == id) {
                playlistSeleccionada = playlist;
                break;
            }
        }
        if (playlistSeleccionada == null) return;
        cargarMusicasEnTabla(playlistSeleccionada.toList());
        listaActualSeleccionada = playlistSeleccionada.getPlaylist();
        lblTituloLista.setText("Playlist: " + playlistSeleccionada.getNombre());
    }

    public int idMusicaActual() {
        int fila = tblMusicas.getSelectedRow();
        if (fila < 0) return 0;
        int idMusicaActual;
        return idMusicaActual = (Integer) tblMusicas.getValueAt(fila, 2);
    }
    
    public Musica musicaActual() {
        Musica musica = listaActualSeleccionada.buscarPorId(idMusicaActual());
        return musica;
    }
    
    public void mostrarDatosDeMusica() {
        lblNombreMusica.setText("<html><div style='width:300px;'>" + musicaActual().getNombre() + "</div></html>");
        lblArtista.setText("<html><div style='width:100px;'>" + musicaActual().getArtista() + "</div></html>");
        lblAlbum.setText("<html><div style='width:100px;'>" + musicaActual().getAlbum() + "</div></html>");
        lblGenero.setText("<html><div style='width:70px;'>" + musicaActual().getGenero() + "</div></html>");
        lblAnio.setText("<html><div style='width:40px;'>" + musicaActual().anioReal() + "</div></html>");
        lblTamanio.setText("<html><div style='width:50px;'>" + musicaActual().formatearTamanio() + "</div></html>");
        
        
    }
    
    public void seleccionarMusicaEnTabla(int id) {
        for (int fila = 0; fila < tblMusicas.getRowCount(); fila++) {
            Object valor = tblMusicas.getValueAt(fila, 2); // columna id
            if (valor != null && Integer.parseInt(valor.toString()) == id) {
                tblMusicas.setRowSelectionInterval(fila, fila);
                break;
            }
        }
    }

    
    private void jmiCargarMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCargarMusicasActionPerformed
        CargaDeMusicas interfazCargaDeMusicas = new CargaDeMusicas(this, true);
        interfazCargaDeMusicas.setVisible(true);
        mostrarBiblioteca();
    }//GEN-LAST:event_jmiCargarMusicasActionPerformed

    private void btnBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBibliotecaActionPerformed
        mostrarBiblioteca();
        tblPlaylist.clearSelection();
    }//GEN-LAST:event_btnBibliotecaActionPerformed

    private void btnNuevaPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaPlaylistActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Nombre de la playlist:");
        if (nombre == null) return; // cancelo
        nombre = nombre.trim();
        if (nombre.isBlank()) {
            JOptionPane.showMessageDialog(this, "Nombre invalido.");
            return;
        }
        if (Biblioteca.getInstance().existePlaylist(nombre)) {
            JOptionPane.showMessageDialog(this, "Ya existe una playlist con ese nombre.");
            return;
        }
        NuevaPlaylist interfazNuevaPlaylist = new NuevaPlaylist(this, true, nombre);
        interfazNuevaPlaylist.setVisible(true);
        mostrarPlaylists();
    }//GEN-LAST:event_btnNuevaPlaylistActionPerformed
    
    private void tblPlaylistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPlaylistMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            abrirPlaylist();
        }
    }//GEN-LAST:event_tblPlaylistMouseClicked

    private void btnPlayPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayPausaActionPerformed
        if (listaActualSeleccionada.seleccionar(musicaActual()) == null) {
            return;
        }

        if (!reproductor.Reproduciendo() && !reproductor.Pausado()) {
            reproductor.Play(listaActualSeleccionada.seleccionar(musicaActual()));
            btnPlayPausa.setText("⏸️");
            mostrarDatosDeMusica();
            return;
        }

        if (reproductor.Reproduciendo()) {
            reproductor.Pausa();
            btnPlayPausa.setText("▶");
            return;
        }

        if (reproductor.Pausado()) {
            reproductor.Reanudar();
            btnPlayPausa.setText("⏸️");
        }
    }//GEN-LAST:event_btnPlayPausaActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if (listaActualSeleccionada.tieneSiguiente()) {
            reproductor.Play(listaActualSeleccionada.siguiente());
            seleccionarMusicaEnTabla(listaActualSeleccionada.getActual().getId());
            mostrarDatosDeMusica();
            btnPlayPausa.setText("⏸️");
            return;
        } else {
            reproductor.Stop();
            btnPlayPausa.setText("▶");
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if (listaActualSeleccionada.tieneAnterior()) {
            reproductor.Play(listaActualSeleccionada.anterior());
            seleccionarMusicaEnTabla(listaActualSeleccionada.getActual().getId());
            mostrarDatosDeMusica();
            btnPlayPausa.setText("⏸️");
            return;
        } else {
            reproductor.Stop();
            btnPlayPausa.setText("▶");
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void tblMusicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMusicasMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            reproductor.Play(listaActualSeleccionada.seleccionar(musicaActual()));
            btnPlayPausa.setText("⏸️");
            mostrarDatosDeMusica();
        }
    }//GEN-LAST:event_tblMusicasMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBiblioteca;
    private javax.swing.JButton btnEditarPlaylist;
    private javax.swing.JButton btnNuevaPlaylist;
    private javax.swing.JButton btnPlayPausa;
    private javax.swing.JButton btnRepetir;
    private javax.swing.JButton btnReproducirLista;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JMenuItem jmiCargarMusicas;
    private javax.swing.JLabel lblAlbum;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNombreMusica;
    private javax.swing.JLabel lblPortada;
    private javax.swing.JLabel lblTamanio;
    private javax.swing.JLabel lblTiempoActual;
    private javax.swing.JLabel lblTituloLista;
    private javax.swing.JLabel lblTxtAlbum;
    private javax.swing.JLabel lblTxtAnio;
    private javax.swing.JLabel lblTxtArtista;
    private javax.swing.JLabel lblTxtGenero;
    private javax.swing.JLabel lblTxtTamanio;
    private javax.swing.JMenu menuAdministrador;
    private javax.swing.JPanel panCanciones;
    private javax.swing.JPanel panPlaylist;
    private javax.swing.JPanel panReproduccion;
    private javax.swing.JSlider sldReproduccion;
    private javax.swing.JTable tblMusicas;
    private javax.swing.JTable tblPlaylist;
    // End of variables declaration//GEN-END:variables
}
