/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smartplayer.interfaz;

import clase.Biblioteca;
import clase.Musica;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import clase.Playlist;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JOptionPane;

/**
 *
 * @author dcuyu
 */
public class InterfazPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName());

    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
        mostrarBibliotecaGeneral();
        refrescarTablaPlaylists();
        tblMusicas.getColumnModel().getColumn(2).setMinWidth(0);
        tblMusicas.getColumnModel().getColumn(2).setMaxWidth(0);
        tblPlaylist.getColumnModel().getColumn(2).setMinWidth(0);
        tblPlaylist.getColumnModel().getColumn(2).setMaxWidth(0);
        tblMusicas.getColumnModel().getColumn(2).setPreferredWidth(0);
        tblPlaylist.getColumnModel().getColumn(0).setMaxWidth(30);
        tblMusicas.getColumnModel().getColumn(0).setMaxWidth(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPlaylist = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPlaylist = new javax.swing.JTable();
        btnBiblioteca = new javax.swing.JButton();
        btnNuevaPlaylist = new javax.swing.JButton();
        btnEditarPlaylist = new javax.swing.JButton();
        panCanciones = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMusicas = new javax.swing.JTable();
        lblTituloMusicas = new javax.swing.JLabel();
        panReproduccion = new javax.swing.JPanel();
        lblNombreMusica = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblAlbum = new javax.swing.JLabel();
        lblTamanio = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        lblPortada = new javax.swing.JLabel();
        sldReproduccion = new javax.swing.JSlider();
        btnPlayPausa = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnRepetir = new javax.swing.JButton();
        jmbMenu = new javax.swing.JMenuBar();
        menuAdministrador = new javax.swing.JMenu();
        jmiCargarMusicas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panPlaylist.setBackground(new java.awt.Color(153, 204, 255));
        panPlaylist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPlaylist.setBackground(new java.awt.Color(121, 245, 248));
        tblPlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Playlist", "Id"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        tblPlaylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPlaylistMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPlaylist);

        panPlaylist.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, 480));

        btnBiblioteca.setBackground(new java.awt.Color(124, 163, 238));
        btnBiblioteca.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnBiblioteca.setText("Biblioteca");
        btnBiblioteca.setToolTipText("");
        btnBiblioteca.setOpaque(true);
        btnBiblioteca.addActionListener(this::btnBibliotecaActionPerformed);
        panPlaylist.add(btnBiblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 40));

        btnNuevaPlaylist.setText("Nueva");
        btnNuevaPlaylist.addActionListener(this::btnNuevaPlaylistActionPerformed);
        panPlaylist.add(btnNuevaPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 110, -1));

        btnEditarPlaylist.setText("Editar");
        panPlaylist.add(btnEditarPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 110, -1));

        panCanciones.setBackground(new java.awt.Color(153, 204, 255));

        tblMusicas.setBackground(new java.awt.Color(255, 255, 224));
        tblMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Musica", "Id"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        tblMusicas.getColumnModel().getColumn(0).setResizable(false);
        jScrollPane1.setViewportView(tblMusicas);

        lblTituloMusicas.setBackground(new java.awt.Color(204, 255, 255));
        lblTituloMusicas.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblTituloMusicas.setText("Nombre");
        lblTituloMusicas.setOpaque(true);

        javax.swing.GroupLayout panCancionesLayout = new javax.swing.GroupLayout(panCanciones);
        panCanciones.setLayout(panCancionesLayout);
        panCancionesLayout.setHorizontalGroup(
            panCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCancionesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(lblTituloMusicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panCancionesLayout.setVerticalGroup(
            panCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCancionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloMusicas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        panReproduccion.setBackground(new java.awt.Color(73, 134, 190));

        lblNombreMusica.setBackground(new java.awt.Color(153, 204, 255));
        lblNombreMusica.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblNombreMusica.setText("Nombre Musica");
        lblNombreMusica.setOpaque(true);

        lblArtista.setBackground(new java.awt.Color(0, 153, 255));
        lblArtista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblArtista.setText("Artista");
        lblArtista.setOpaque(true);

        lblGenero.setBackground(new java.awt.Color(0, 153, 255));
        lblGenero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGenero.setText("Genero");
        lblGenero.setOpaque(true);

        lblAlbum.setBackground(new java.awt.Color(0, 153, 255));
        lblAlbum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAlbum.setText("Album");
        lblAlbum.setOpaque(true);

        lblTamanio.setBackground(new java.awt.Color(0, 153, 255));
        lblTamanio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTamanio.setText("Tamaño");
        lblTamanio.setOpaque(true);

        lblAnio.setBackground(new java.awt.Color(0, 153, 255));
        lblAnio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAnio.setText("Año");
        lblAnio.setOpaque(true);

        lblPortada.setText(".");
        lblPortada.setOpaque(true);

        sldReproduccion.setValue(0);
        sldReproduccion.setUI(new javax.swing.plaf.basic.BasicSliderUI(sldReproduccion) {
            @Override
            public void paintThumb(Graphics g) {
                Graphics2D g2d = (Graphics2D) g;
                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                // Color de la bolita
                g2d.setColor(new java.awt.Color(0, 122, 255));

                // Forzamos un tamaño idéntico para que sea un círculo perfecto (16x16 píxeles)
                int diametro = 16;

                // Centramos la bolita verticalmente en el espacio disponible
                int x = thumbRect.x + (thumbRect.width - diametro) / 2;
                int y = thumbRect.y + (thumbRect.height - diametro) / 2;

                // Dibujamos el círculo perfecto
                g2d.fillOval(x, y, diametro, diametro);
            }
        });

        btnPlayPausa.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        btnPlayPausa.setText("▶");
        btnPlayPausa.setActionCommand("");

        btnSiguiente.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        btnSiguiente.setText("⏭");

        btnAnterior.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        btnAnterior.setText("⏮");

        btnRepetir.setFont(new java.awt.Font("Segoe UI Symbol", 1, 10)); // NOI18N
        btnRepetir.setText("🔁");

        javax.swing.GroupLayout panReproduccionLayout = new javax.swing.GroupLayout(panReproduccion);
        panReproduccion.setLayout(panReproduccionLayout);
        panReproduccionLayout.setHorizontalGroup(
            panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panReproduccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panReproduccionLayout.createSequentialGroup()
                        .addComponent(lblPortada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panReproduccionLayout.createSequentialGroup()
                        .addComponent(lblNombreMusica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panReproduccionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(lblAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(panReproduccionLayout.createSequentialGroup()
                        .addComponent(lblTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(panReproduccionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panReproduccionLayout.createSequentialGroup()
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPlayPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRepetir)
                        .addGap(7, 7, 7))
                    .addComponent(sldReproduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panReproduccionLayout.setVerticalGroup(
            panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panReproduccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlbum)
                    .addComponent(lblArtista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTamanio)
                    .addComponent(lblAnio)
                    .addComponent(lblGenero))
                .addGap(12, 12, 12)
                .addComponent(lblPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sldReproduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(btnPlayPausa, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnRepetir))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        menuAdministrador.setText("Administrador");

        jmiCargarMusicas.setText("Cargar musicas");
        jmiCargarMusicas.addActionListener(this::jmiCargarMusicasActionPerformed);
        menuAdministrador.add(jmiCargarMusicas);

        jmbMenu.add(menuAdministrador);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panReproduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panReproduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void refrescarTablaPlaylists() {
        DefaultTableModel modelo = (DefaultTableModel) tblPlaylist.getModel();
        modelo.setRowCount(0);

        List<Playlist> playlists = Biblioteca.getInstance().getPlaylists();
        int no = 1;
        for (Playlist p : playlists) {
            modelo.addRow(new Object[]{ no++, p.getNombre(), p.getId() });
        }
    }
    
    private void cargarEnTablaMusicas(List<Musica> musicas) {
        DefaultTableModel modelo = (DefaultTableModel) tblMusicas.getModel();
        modelo.setRowCount(0);
        lblTituloMusicas.setText("Biblioteca");
        int no = 1;
        for (Musica m : musicas) {
            modelo.addRow(new Object[]{ no++, m.toString(), m.getId() });
        }
    }

    private void mostrarBibliotecaGeneral() {
        cargarEnTablaMusicas(
            Biblioteca.getInstance().getListaGeneral().toListAdelante()
        );
    }
    
    private void jmiCargarMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCargarMusicasActionPerformed
        InterfazCargaDeMusicas interfaz = new InterfazCargaDeMusicas(this, true);
        interfaz.setVisible(true);
        mostrarBibliotecaGeneral();
    }//GEN-LAST:event_jmiCargarMusicasActionPerformed

    private void btnBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBibliotecaActionPerformed
        mostrarBibliotecaGeneral();
        tblPlaylist.clearSelection();
    }//GEN-LAST:event_btnBibliotecaActionPerformed

    private void btnNuevaPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaPlaylistActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Nombre de la playlist:");
        if (nombre == null) return; // canceló
        nombre = nombre.trim();
        if (nombre.isBlank()) {
            JOptionPane.showMessageDialog(this, "Nombre invalido.");
            return;
        }
        if (Biblioteca.getInstance().existePlaylist(nombre)) {
            JOptionPane.showMessageDialog(this, "Ya existe una playlist con ese nombre.");
            return;
        }
        InterfazNuevaPlaylist interfaz = new InterfazNuevaPlaylist(this, true, nombre);
        interfaz.setVisible(true);
        refrescarTablaPlaylists();
    }//GEN-LAST:event_btnNuevaPlaylistActionPerformed

    private void abrirPlaylistSeleccionada() {
        int fila = tblPlaylist.getSelectedRow();
        if (fila < 0) return;
        int id = (Integer) tblPlaylist.getValueAt(fila, 2);

        Playlist seleccionada = null;
        for (Playlist p : Biblioteca.getInstance().getPlaylists()) {
            if (p.getId() == id) {
                seleccionada = p;
                break;
            }
        }
        if (seleccionada == null) return;

        List<Musica> canciones = seleccionada.toList(); // Mostrar canciones de la playlist en la tabla de musicas
        DefaultTableModel modelo = (DefaultTableModel) tblMusicas.getModel();
        modelo.setRowCount(0);
        lblTituloMusicas.setText("Playlist: " + seleccionada.getNombre());
        int no = 1;
        for (Musica m : canciones) {
            modelo.addRow(new Object[]{ no++, m.toString(), m.getId() });
        }
    }
    
    private void tblPlaylistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPlaylistMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            abrirPlaylistSeleccionada();
        }
    }//GEN-LAST:event_tblPlaylistMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBiblioteca;
    private javax.swing.JButton btnEditarPlaylist;
    private javax.swing.JButton btnNuevaPlaylist;
    private javax.swing.JButton btnPlayPausa;
    private javax.swing.JButton btnRepetir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JMenuItem jmiCargarMusicas;
    private javax.swing.JLabel lblAlbum;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNombreMusica;
    private javax.swing.JLabel lblPortada;
    private javax.swing.JLabel lblTamanio;
    private javax.swing.JLabel lblTituloMusicas;
    private javax.swing.JMenu menuAdministrador;
    private javax.swing.JPanel panCanciones;
    private javax.swing.JPanel panPlaylist;
    private javax.swing.JPanel panReproduccion;
    private javax.swing.JSlider sldReproduccion;
    private javax.swing.JTable tblMusicas;
    private javax.swing.JTable tblPlaylist;
    // End of variables declaration//GEN-END:variables
}
