/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package smartplayer.interfaz;

import clase.Biblioteca;
import clase.Playlist;
import javax.swing.JOptionPane;
import clase.Musica;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dcuyu
 */
public class InterfazNuevaPlaylist extends javax.swing.JDialog {
    private final String nombrePlaylist;
    private final java.util.List<Musica> seleccionadas = new java.util.ArrayList<>();
    private final java.util.Set<Integer> idsSeleccionadas = new java.util.HashSet<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazNuevaPlaylist.class.getName());

    /**
     * Creates new form InterfazNuevaPlaylist
     */
    public InterfazNuevaPlaylist(java.awt.Frame parent, boolean modal, String nombrePlaylist) {
        super(parent, modal);
        initComponents();
        tblMusicas.getColumnModel().getColumn(0).setMaxWidth(30);
        tblMusicasPlaylist.getColumnModel().getColumn(0).setMaxWidth(30);
        // Ocultar columna ID (ultima, indice 5)
        tblMusicas.getColumnModel().getColumn(5).setMinWidth(0);
        tblMusicas.getColumnModel().getColumn(5).setMaxWidth(0);
        tblMusicas.getColumnModel().getColumn(5).setPreferredWidth(0);
        this.nombrePlaylist = nombrePlaylist;
        lblNombrePlaylist.setText(nombrePlaylist);
        cargarBibliotecaEnTabla();
        cargarSeleccionadasEnTabla();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombrePlaylist = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMusicasPlaylist = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMusicas = new javax.swing.JTable();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNombrePlaylist.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblNombrePlaylist.setText("Playlist");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Biblioteca");

        tblMusicasPlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nombre"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        jScrollPane1.setViewportView(tblMusicasPlaylist);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Musicas en la Playlist");

        tblMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nombre", "Artista", "Album", "Genero", "Id"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        jScrollPane3.setViewportView(tblMusicas);

        btnBuscar.setText("Buscar");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAgregar)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(99, 99, 99)
                            .addComponent(btnGuardar)
                            .addGap(14, 14, 14)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnGuardar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNombrePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombrePlaylist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarSeleccionadasEnTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblMusicasPlaylist.getModel();
        modelo.setRowCount(0);

        int no = 1;
        for (Musica m : seleccionadas) {
            modelo.addRow(new Object[]{ no++, m.getNombre() });
        }
    }
    
    private void cargarBibliotecaEnTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblMusicas.getModel();
        modelo.setRowCount(0);
        List<Musica> musicas = Biblioteca.getInstance().getListaGeneral().toListAdelante();
        int no = 1;
        for (Musica m : musicas) {
            modelo.addRow(new Object[]{
                no++,
                m.getNombre(),
                m.getArtista(),
                m.getAlbum(),
                m.getGenero(),
                m.getId()     // <- aqui va el ID oculto
            });
        }
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (seleccionadas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Agrega al menos una musica antes de guardar.");
            return;
        }
        Playlist p = Biblioteca.getInstance().crearPlaylist(nombrePlaylist);
        if (p == null) {
            // por seguridad: por si se creó en otra parte o el nombre se volvió inválido
            JOptionPane.showMessageDialog(this, "No se pudo crear: nombre invalido o duplicado.");
            return;
        }
        for (Musica m : seleccionadas) {
            p.agregarSiNoExiste(m); // extra seguridad (aunque ya evitamos duplicados)
        }
        dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int[] filas = tblMusicas.getSelectedRows();
        if (filas.length == 0) {
            JOptionPane.showMessageDialog(this, "Selecciona una o mas musicas de la biblioteca.");
            return;
        }

        List<Musica> biblioteca = Biblioteca.getInstance().getListaGeneral().toListAdelante();// Para no recorrer la biblioteca por cada fila, la convertimos una sola vez
        int agregadas = 0;
        int repetidas = 0;
        int noEncontradas = 0;

        for (int fila : filas) {
            Object val = tblMusicas.getValueAt(fila, 5); // id oculto
            int id = Integer.parseInt(val.toString());
            Musica seleccionada = null;
            for (Musica x : biblioteca) {
                if (x.getId() == id) {
                    seleccionada = x;
                    break;
                }
            }

            if (seleccionada == null) {
                noEncontradas++;
                continue;
            }

            if (!idsSeleccionadas.add(seleccionada.getId())) {
                repetidas++;
                continue;
            }

            seleccionadas.add(seleccionada);
            agregadas++;
        }
        cargarSeleccionadasEnTabla();
        
        if (repetidas > 0 || noEncontradas > 0) {
            JOptionPane.showMessageDialog(this,
                    "Agregadas: " + agregadas +
                    "\nRepetidas ignoradas: " + repetidas +
                    "\nNo encontradas: " + noEncontradas);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNombrePlaylist;
    private javax.swing.JTable tblMusicas;
    private javax.swing.JTable tblMusicasPlaylist;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
