/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smartplayer.interfaz;

import clase.Biblioteca;
import clase.Musica;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import clase.Playlist;
import javax.swing.JOptionPane;

/**
 *
 * @author dcuyu
 */
public class InterfazPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName());

    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
        mostrarBibliotecaGeneral();
        refrescarTablaPlaylists();
        tblMusicas.getColumnModel().getColumn(2).setMinWidth(0);
        tblMusicas.getColumnModel().getColumn(2).setMaxWidth(0);
        tblMusicas.getColumnModel().getColumn(2).setPreferredWidth(0);
        tblPlaylist.getColumnModel().getColumn(0).setMaxWidth(30);
        tblMusicas.getColumnModel().getColumn(0).setMaxWidth(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPlaylist = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPlaylist = new javax.swing.JTable();
        btnBiblioteca = new javax.swing.JButton();
        btnNuevaPlaylist = new javax.swing.JButton();
        btnEditarPlaylist = new javax.swing.JButton();
        panCanciones = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMusicas = new javax.swing.JTable();
        lblTituloMusicas = new javax.swing.JLabel();
        panReproduccion = new javax.swing.JPanel();
        jmbMenu = new javax.swing.JMenuBar();
        menuAdministrador = new javax.swing.JMenu();
        jmiCargarMusicas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panPlaylist.setBackground(new java.awt.Color(153, 204, 255));
        panPlaylist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPlaylist.setBackground(new java.awt.Color(121, 245, 248));
        tblPlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Playlist"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        tblPlaylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPlaylistMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPlaylist);

        panPlaylist.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, 480));

        btnBiblioteca.setBackground(new java.awt.Color(124, 163, 238));
        btnBiblioteca.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btnBiblioteca.setText("Biblioteca");
        btnBiblioteca.setToolTipText("");
        btnBiblioteca.setOpaque(true);
        btnBiblioteca.addActionListener(this::btnBibliotecaActionPerformed);
        panPlaylist.add(btnBiblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 40));

        btnNuevaPlaylist.setText("Nueva");
        btnNuevaPlaylist.addActionListener(this::btnNuevaPlaylistActionPerformed);
        panPlaylist.add(btnNuevaPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 110, -1));

        btnEditarPlaylist.setText("Editar");
        panPlaylist.add(btnEditarPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 110, -1));

        panCanciones.setBackground(new java.awt.Color(153, 204, 255));

        tblMusicas.setBackground(new java.awt.Color(255, 255, 224));
        tblMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Musica", "Id"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        tblMusicas.getColumnModel().getColumn(0).setResizable(false);
        jScrollPane1.setViewportView(tblMusicas);

        lblTituloMusicas.setBackground(new java.awt.Color(204, 255, 255));
        lblTituloMusicas.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblTituloMusicas.setText("Nombre");
        lblTituloMusicas.setOpaque(true);

        javax.swing.GroupLayout panCancionesLayout = new javax.swing.GroupLayout(panCanciones);
        panCanciones.setLayout(panCancionesLayout);
        panCancionesLayout.setHorizontalGroup(
            panCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCancionesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(lblTituloMusicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panCancionesLayout.setVerticalGroup(
            panCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCancionesLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblTituloMusicas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panReproduccion.setBackground(new java.awt.Color(73, 134, 190));

        javax.swing.GroupLayout panReproduccionLayout = new javax.swing.GroupLayout(panReproduccion);
        panReproduccion.setLayout(panReproduccionLayout);
        panReproduccionLayout.setHorizontalGroup(
            panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );
        panReproduccionLayout.setVerticalGroup(
            panReproduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menuAdministrador.setText("Administrador");

        jmiCargarMusicas.setText("Cargar musicas");
        jmiCargarMusicas.addActionListener(this::jmiCargarMusicasActionPerformed);
        menuAdministrador.add(jmiCargarMusicas);

        jmbMenu.add(menuAdministrador);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panReproduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panCanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panPlaylist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panReproduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void refrescarTablaPlaylists() {
        DefaultTableModel modelo = (DefaultTableModel) tblPlaylist.getModel();
        modelo.setRowCount(0);

        List<Playlist> playlists = Biblioteca.getInstance().getPlaylists();
        int no = 1;
        for (Playlist p : playlists) {
            modelo.addRow(new Object[]{ no++, p.getNombre() });
        }
    }
    
    private void cargarEnTablaMusicas(List<Musica> musicas) {
        DefaultTableModel modelo = (DefaultTableModel) tblMusicas.getModel();
        modelo.setRowCount(0);
        lblTituloMusicas.setText("Biblioteca");
        int no = 1;
        for (Musica m : musicas) {
            modelo.addRow(new Object[]{ no++, m.toString(), m.getId() });
        }
    }

    private void mostrarBibliotecaGeneral() {
        cargarEnTablaMusicas(
            Biblioteca.getInstance().getListaGeneral().toListAdelante()
        );
    }
    
    private void jmiCargarMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCargarMusicasActionPerformed
        InterfazCargaDeMusicas interfaz = new InterfazCargaDeMusicas(this, true);
        interfaz.setVisible(true);
        mostrarBibliotecaGeneral();
    }//GEN-LAST:event_jmiCargarMusicasActionPerformed

    private void btnBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBibliotecaActionPerformed
        mostrarBibliotecaGeneral();
        tblPlaylist.clearSelection();
    }//GEN-LAST:event_btnBibliotecaActionPerformed

    private void btnNuevaPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaPlaylistActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Nombre de la playlist:");
        if (nombre == null) return; // canceló
        nombre = nombre.trim();
        if (nombre.isBlank()) {
            JOptionPane.showMessageDialog(this, "Nombre invalido.");
            return;
        }
        if (Biblioteca.getInstance().existePlaylist(nombre)) {
            JOptionPane.showMessageDialog(this, "Ya existe una playlist con ese nombre.");
            return;
        }
        InterfazNuevaPlaylist interfaz = new InterfazNuevaPlaylist(this, true, nombre);
        interfaz.setVisible(true);
        refrescarTablaPlaylists();
    }//GEN-LAST:event_btnNuevaPlaylistActionPerformed

    private void abrirPlaylistSeleccionada() {
        int fila = tblPlaylist.getSelectedRow();
        if (fila < 0) return;
        String nombre = tblPlaylist.getValueAt(fila, 1).toString();

        Playlist seleccionada = null;
        for (Playlist p : Biblioteca.getInstance().getPlaylists()) {
            if (p.getNombre().equalsIgnoreCase(nombre)) {
                seleccionada = p;
                break;
            }
        }
        if (seleccionada == null) return;

        List<Musica> canciones = seleccionada.toList(); // Mostrar canciones de la playlist en la tabla de musicas
        DefaultTableModel modelo = (DefaultTableModel) tblMusicas.getModel();
        modelo.setRowCount(0);
        lblTituloMusicas.setText("Playlist: " + seleccionada.getNombre());
        int no = 1;
        for (Musica m : canciones) {
            modelo.addRow(new Object[]{ no++, m.toString(), m.getId() });
        }
    }
    
    private void tblPlaylistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPlaylistMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            abrirPlaylistSeleccionada();
        }
    }//GEN-LAST:event_tblPlaylistMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBiblioteca;
    private javax.swing.JButton btnEditarPlaylist;
    private javax.swing.JButton btnNuevaPlaylist;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JMenuItem jmiCargarMusicas;
    private javax.swing.JLabel lblTituloMusicas;
    private javax.swing.JMenu menuAdministrador;
    private javax.swing.JPanel panCanciones;
    private javax.swing.JPanel panPlaylist;
    private javax.swing.JPanel panReproduccion;
    private javax.swing.JTable tblMusicas;
    private javax.swing.JTable tblPlaylist;
    // End of variables declaration//GEN-END:variables
}
